language: objective-c
osx_image: xcode8.0
xcode_workspace: GoT_wiki.xcworkspace
xcode_scheme: allTests
xcode_sdk: iphonesimulator9.3
branches:
  only:
    - master
    - develop
    - /^release\/[\w\.]+$/
install:
  - pod repo update
  - pod install
after_success:
  - bash <(curl -s https://codecov.io/bash)
cache:
  - cocoapods
