language: objective-c
osx_image: xcode7.3
xcode_workspace: GoT_wiki.xcworkspace
xcode_scheme: GoT_wiki
xcode_sdk: iphonesimulator9.3
branches:
  only:
    - master
    - develop
    - /^release\/[\w\.]+$/
install:
  - rvm install 2.2.2
  - rvm use 2.2.2
  - gem install cocoapods
  - pod install
script:
  - bash runUITest.sh
  - xctool
after_success:
  - bash <(curl -s https://codecov.io/bash)
cache:
  - cocoapods
