language: objective-c
osx_image: xcode7.3
xcode_workspace: GoT_wiki.xcworkspace
xcode_scheme: GoT_wiki
branches:
  only:
    - master
    - develop
    - /^release\/[\w\.]+$/
install:
  - pod repo update
  - pod install
after_success:
  - bash <(curl -s https://codecov.io/bash)

